### ISSUE TITLE
Test does not run on latest node 4 version

### ISSUE THREAD

**Issue by moffe42** [ColourboxDevelopment/weeklyplan#1]
All tests run on node v.4.4.5, but not on latest node (v.4.5.0)

```
> jest

● The `unmockedModulePathPatterns` setting is defined but automocking is disabled in Jest. Please either remove `unmockedModulePathPatterns` from your configuration or explicitly set `"automock": true` in your configuration if you wish to use automocking.

  Jest 15 changed the default configuration for tests and makes Jest easier to
  use and less confusing for beginners. All previous defaults can be restored
  if your project depends on it. A comprehensive explanation of the breaking
  changes and an upgrade guide can be found in the release blog post linked
  below.

  Jest Issue Tracker: https://github.com/facebook/jest/issues
  Configuration Documentation: https://facebook.github.io/jest/docs/api.html
  Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html

  console.warn node_modules/jest-cli/node_modules/jest-runtime/build/index.js:647
    jest.unmock('../components/DeactivateUserButton.jsx') was called but automocking is disabled. Remove the unnecessary call to `jest.unmock` or enable automocking for this test via `jest.enableAutomock();`. This warning is likely a result of a default configuration change in Jest 15.

    Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html

  console.warn node_modules/jest-cli/node_modules/jest-runtime/build/index.js:647
    jest.unmock('../stores/store.js') was called but automocking is disabled. Remove the unnecessary call to `jest.unmock` or enable automocking for this test via `jest.enableAutomock();`. This warning is likely a result of a default configuration change in Jest 15.

    Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html

  console.warn node_modules/jest-cli/node_modules/jest-runtime/build/index.js:647
    jest.unmock('../stores/user.js') was called but automocking is disabled. Remove the unnecessary call to `jest.unmock` or enable automocking for this test via `jest.enableAutomock();`. This warning is likely a result of a default configuration change in Jest 15.

    Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html

 FAIL  public/js/__tests__/DeactivateUserButton-test.js
  DeactivateUserButton
    ✓ has callback mocked correctly (304ms)
    ✕ invokes callback with user on click (31ms)
    ✕ consists of a danger button with a ban icon (12ms)
    ✕ integrates with actions and store (5ms)

  ● DeactivateUserButton › invokes callback with user on click

    TypeError: Cannot read property '0' of undefined

      at Object.<anonymous> (public/js/__tests__/DeactivateUserButton-test.js:22:47)

  ● DeactivateUserButton › consists of a danger button with a ban icon

    TypeError: Cannot read property '0' of undefined

      at Object.<anonymous> (public/js/__tests__/DeactivateUserButton-test.js:22:47)

  ● DeactivateUserButton › integrates with actions and store

    TypeError: Cannot read property '0' of undefined

      at Object.<anonymous> (public/js/__tests__/DeactivateUserButton-test.js:22:47)

Test Summary
 › Ran all tests.
 › 3 tests failed, 1 test passed (4 total in 1 test suite, run time 5.831s)
npm ERR! Test failed.  See above for more details.
```

**Comment by moffe42** [comment]
I downgraded the version of jest used to to v13. For some reason v14 return 1 on success. But the code should still be fixed.
